// general-backend-management-system-vue/src/App.vue
<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
  <div class="router-area">
    <router-link to="/" style="margin-right: 10px">{{ t('message.home') }}</router-link>
    <router-link to="/about">{{ t('message.about') }}</router-link>
    <router-view></router-view>
  </div>
  <div class="ant-area">
    <Button type="primary" :icon="h(SyncOutlined)" @click="switchLang">Antd Button</Button>
  </div>
</template>

<script setup lang="ts">
import { Button } from 'ant-design-vue';
import { SyncOutlined } from '@ant-design/icons-vue';
import HelloWorld from './components/HelloWorld.vue';
import { h } from 'vue';
import { useI18n } from 'vue-i18n';

const { t, locale } = useI18n();

function switchLang() {
  locale.value = locale.value === 'en' ? 'zh' : 'en';
}
</script>

<style scoped lang="scss">
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}

$bgc-router: #e2b050;
.router-area {
  margin-top: 20px;
  background-color: $bgc-router;
}
</style>

// general-backend-management-system-react/src/App.tsx
import './App.css';

import { SwapOutlined } from '@ant-design/icons';
import { Button, Space } from 'antd';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, Outlet } from 'react-router';

import viteLogo from '/vite.svg';

import reactLogo from './assets/react.svg';

function App() {
  const [count, setCount] = useState(0);

  const { t, i18n } = useTranslation();

  const switchLang = () => {
    i18n.changeLanguage(i18n.language === 'zh' ? 'en' : 'zh');
  };

  return (
    <>
      <h1>{t('message.hello')}</h1>
      <Button type={'primary'} icon={<SwapOutlined />} onClick={switchLang}>
        switch lang
      </Button>
      <div>
        <a href="https://vite.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the Vite and React logos to learn more</p>
      <div>
        <Space>
          <Link to="/home">Home</Link>
          <Link to="/about">About</Link>
        </Space>
        <Outlet />
      </div>
    </>
  );
}

export default App;
