// general-backend-management-system-react/src/components/lang-switch/LangSwitch.tsx
import { TranslationOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { Button, Dropdown } from 'antd';
import { useTranslation } from 'react-i18next';

const dropdownMenuItems: MenuProps['items'] = [
  { key: 'zh', label: '简体中文' },
  { key: 'en', label: 'English' },
];

export default function LangSwitch() {
  const { t, i18n } = useTranslation();

  const switchLang = ({ key }: any) => i18n.changeLanguage(key);

  return (
    <Dropdown menu={{ items: dropdownMenuItems, onClick: switchLang }}>
      <Button type={'link'} icon={<TranslationOutlined />}>
        {t('login.header.switchLang')}
      </Button>
    </Dropdown>
  );
}

// general-backend-management-system-vue/src/components/LangSwitch.vue
<template>
  <Dropdown v-model:open="dropdownVisible">
    <Button type="link" :icon="h(TranslationOutlined)">
      {{ t('login.header.switchLang') }}
    </Button>

    <template #overlay>
      <Menu @click="handleMenuClick">
        <MenuItem key="zh">简体中文</MenuItem>
        <MenuItem key="en">English</MenuItem>
      </Menu>
    </template>
  </Dropdown>
</template>

<script setup lang="ts">
import { TranslationOutlined } from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, MenuItem } from 'ant-design-vue';
import { h, ref } from 'vue';
import { useI18n } from 'vue-i18n';

const { t, locale } = useI18n();
const dropdownVisible = ref(false);

function handleMenuClick(e: any) {
  locale.value = e.key;
  dropdownVisible.value = false;
}
</script>

<style scoped lang="scss"></style>
