// general-backend-management-system-vue/src/pages/login/LoginRegisterPanel.vue
<template>
  <Card class="panel-container">
    <Tabs v-model:active-key="activeTabKey" centered size="large" @change="onTabsChange">
      <TabPane key="login" :tab="t('login.content.login')"></TabPane>
      <TabPane key="register" :tab="t('login.content.register')"></TabPane>
    </Tabs>
    <LoginRegisterForm
      ref="loginRegFormRef"
      :form-type="activeTabKey"
      class="login-reg-form"
      @switch-tab="switchTab"
    />
  </Card>
</template>

<script setup lang="ts">
import { Card, TabPane, Tabs } from 'ant-design-vue';
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';

import type { LoginRegisterFormType } from '@/pages/login/LoginRegisterForm.vue';
import LoginRegisterForm from '@/pages/login/LoginRegisterForm.vue';

const { t } = useI18n();
const activeTabKey = ref<LoginRegisterFormType>('login');
const loginRegFormRef = ref(null);

function switchTab(tab: LoginRegisterFormType) {
  onTabsChange();
  activeTabKey.value = tab;
}

function onTabsChange() {
  loginRegFormRef.value?.resetForm();
}
</script>

<style scoped lang="scss">
.panel-container {
  width: 400px;
  background-color: #fff;

  .login-reg-form {
    margin-top: 10px;
  }
}

:deep(.ant-tabs-nav-list) {
  width: 100%;

  .ant-tabs-tab {
    width: 50%;
    display: flex;
    justify-content: center;
  }

  .ant-tabs-ink-bar {
    width: 50%;
  }
}
</style>

// general-backend-management-system-react/src/pages/login/LoginRegisterPanel.tsx
import { Card, Tabs } from 'antd';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';

import type { LoginRegisterFormType } from '@/pages/login/LoginRegisterForm.tsx';
import LoginRegisterForm from '@/pages/login/LoginRegisterForm.tsx';

import styles from './LoginRegisterPanel.module.scss';

export default function LoginRegisterPanel() {
  const { t } = useTranslation();
  const [activeTabKey, setActiveTabKey] = useState<LoginRegisterFormType>('login');

  const tabItems = [
    { label: t('login.content.login'), key: 'login' },
    { label: t('login.content.register'), key: 'register' },
  ];

  function handleTabChange(activeKey: string) {
    setActiveTabKey(activeKey as LoginRegisterFormType);
  }

  return (
    <Card className={styles['login-panel-card']}>
      <Tabs
        activeKey={activeTabKey}
        items={tabItems}
        size={'large'}
        tabBarStyle={{ width: '100%' }}
        centered
        onChange={handleTabChange}
      />
      <LoginRegisterForm formType={activeTabKey} switchTab={handleTabChange} />
    </Card>
  );
}
