// general-backend-management-system-react/src/components/nav-header/MessageModal.tsx
import { MailOutlined } from '@ant-design/icons';
import { Button, Modal } from 'antd';
import { useState } from 'react';

import styles from './MessageModal.module.scss';

interface MessageModalProps {
  className: string;
}

export default function MessageModal({ className }: MessageModalProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);

  function showModal() {
    setIsModalOpen(true);
  }

  function hideModal() {
    setIsModalOpen(false);
  }

  function handleOk() {
    hideModal();
  }

  return (
    <div className={`${className} ${styles['container']}`}>
      <Button
        type={'link'}
        icon={<MailOutlined />}
        onClick={showModal}
        className={styles['open-btn']}
      />

      <Modal
        title={'部门消息'}
        open={isModalOpen}
        maskClosable={false}
        onOk={handleOk}
        onCancel={hideModal}
      >
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur autem consectetur cum
          delectus distinctio dolorem doloremque dolores fugit harum itaque molestias mollitia
          perferendis quasi quisquam rerum ullam, unde? Consequatur, perferendis.
        </p>
      </Modal>
    </div>
  );
}

// general-backend-management-system-vue/src/components/header/MessageModal.vue
<template>
  <Button type="link" :icon="h(MailOutlined)" size="large" @click="openModal" />
  <Modal v-model:open="modalVisible" title="部门消息" centered @ok="closeModal">
    <div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto facilis laborum mollitia
      necessitatibus odit officiis sunt ut vero, voluptatem voluptatibus! A aspernatur consectetur
      debitis fuga harum recusandae sint ullam vero!
    </div>

    <template #footer>
      <Flex justify="center">
        <Button type="primary" @click="closeModal">OK</Button>
      </Flex>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { MailOutlined } from '@ant-design/icons-vue';
import { Button, Flex, Modal } from 'ant-design-vue';
import { h, ref } from 'vue';

const modalVisible = ref(false);

function openModal() {
  modalVisible.value = true;
}

function closeModal() {
  modalVisible.value = false;
}
</script>

<style scoped lang="scss"></style>
