// general-backend-management-system-react/src/pages/login/LoginRegisterForm.tsx
import { Button, Flex, Form, Input, message } from 'antd';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router';

import type { LoginRegisterDataType } from '@/api/LoginRegister.ts';
import { login, register } from '@/api/LoginRegister.ts';
import { useValidationRules } from '@/pages/login/loginRegisterCommon.ts';
import ResetPwdModal from '@/pages/login/ResetPwdModal.tsx';

import styles from './LoginRegisterForm.module.scss';

export type LoginRegisterFormType = 'login' | 'register';

interface LoginRegisterFormProps {
  formType: LoginRegisterFormType;
  switchTab: (tabKey: LoginRegisterFormType) => void;
}

interface LoginRegisterFormData {
  username: string;
  password: string;
  passwordConfirm?: string;
}

type FormRules = Record<keyof LoginRegisterFormData, any[]>;

const { Item: FormItem } = Form;
const { Password } = Input;
const actionMap = { login, register };

export default function LoginRegisterForm({ formType, switchTab }: LoginRegisterFormProps) {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const [messageApi, contextHolder] = message.useMessage();
  const [loginRegisterForm] = Form.useForm();
  const [formData, setFormData] = useState<LoginRegisterFormData>({
    username: '',
    password: '',
    passwordConfirm: '',
  });

  const validationRules = useValidationRules(formData);
  const formRules: FormRules = useMemo(() => {
    const { username, password, confirmPwd } = validationRules;
    const commonRules = { username, password } as FormRules;

    if (formType === 'login') return commonRules;
    return { ...commonRules, passwordConfirm: confirmPwd };
  }, [formType, validationRules]);

  function handleFormDataChange(fieldName: keyof LoginRegisterFormData, value: string) {
    setFormData((prev) => ({ ...prev, [fieldName]: value }));
  }

  function handleSubmit() {
    loginRegisterForm.validateFields().then(async (values) => {
      console.log(values);
      const { username, password } = values;
      const data: LoginRegisterDataType = { username, password };

      const res: any = await actionMap[formType](data);
      const space = i18n.language === 'zh' ? '' : ' ';
      if (res.status === 0) {
        messageApi.success(
          `${t('login.content.' + formType)}${space}${t('login.content.success')}`,
        );
        formType === 'login' && navigate('/admin', { replace: true });
      } else {
        messageApi.error(`${t('login.content.' + formType)}${space}${t('login.content.fail')}`);
      }
    });
  }

  return (
    <>
      {contextHolder} {/* 必须放在组件中，用于挂载 message 容器 */}
      <Form layout={'vertical'} form={loginRegisterForm} autoComplete={'off'}>
        <FormItem
          name={'username'}
          label={t('login.content.username')}
          rules={formRules.username}
          validateTrigger={['onBlur', 'onChange']}
          validateFirst
        >
          <Input
            placeholder={t('login.content.usernamePlaceholder')}
            onChange={(e) => handleFormDataChange('username', e.target.value)}
          />
        </FormItem>
        <FormItem
          name={'password'}
          label={t('login.content.password')}
          rules={formRules.password}
          validateTrigger={['onBlur', 'onChange']}
          validateFirst
        >
          <Password
            placeholder={t('login.content.passwordPlaceholder')}
            onChange={(e) => handleFormDataChange('password', e.target.value)}
          />
        </FormItem>
        {formType === 'register' && (
          <FormItem
            name={'passwordConfirm'}
            label={t('login.content.passwordConfirm')}
            rules={formRules.passwordConfirm}
            validateTrigger={['onBlur']}
            validateFirst
          >
            <Password
              placeholder={t('login.content.passwordConfirmPlaceholder')}
              onChange={(e) => handleFormDataChange('passwordConfirm', e.target.value)}
            />
          </FormItem>
        )}
      </Form>
      {formType === 'login' && (
        <Flex justify={'flex-end'}>
          <ResetPwdModal />
        </Flex>
      )}
      <Button
        type={'primary'}
        size={'large'}
        className={styles['login-reg-button']}
        onClick={handleSubmit}
      >
        {t(`login.content.${formType}`)}
      </Button>
      {formType === 'login' && (
        <Flex justify={'center'} align={'center'} className={styles['go-reg-bar']}>
          <span>{t('login.content.noAccount')}</span>
          <Button
            type={'link'}
            size={'small'}
            className={styles['go-reg-button']}
            onClick={() => switchTab(formType === 'login' ? 'register' : 'login')}
          >
            {t('login.content.registerNow')}
          </Button>
        </Flex>
      )}
    </>
  );
}

// general-backend-management-system-vue/src/pages/login/LoginRegisterForm.vue
<template>
  <div class="login-form-container">
    <Form ref="loginRegFormRef" :model="loginRegFormData" :rules="rules" layout="vertical">
      <FormItem :label="t('login.content.username')" name="username">
        <Input
          v-model:value="loginRegFormData.username"
          :placeholder="t('login.content.usernamePlaceholder')"
          allow-clear
        />
      </FormItem>
      <FormItem :label="t('login.content.password')" name="password">
        <Input
          v-model:value="loginRegFormData.password"
          :placeholder="t('login.content.passwordPlaceholder')"
          type="password"
          allow-clear
        />
      </FormItem>
      <FormItem
        v-if="formType === 'register'"
        :label="t('login.content.passwordConfirm')"
        name="passwordConfirm"
      >
        <Input
          v-model:value="loginRegFormData.passwordConfirm"
          :placeholder="t('login.content.passwordConfirmPlaceholder')"
          type="password"
          allow-clear
        />
      </FormItem>
    </Form>

    <Flex v-if="formType === 'login'" justify="flex-end">
      <ResetPwdModal />
    </Flex>

    <Button type="primary" class="login-button" @click="submit">
      {{ submitBtnText[formType] }}
    </Button>

    <Flex v-if="formType === 'login'" justify="center" align="center">
      <span>{{ t('login.content.noAccount') }}</span>
      <Button type="link" size="small" @click="() => switchTab('register')">
        {{ t('login.content.registerNow') }}
      </Button>
    </Flex>
  </div>
</template>

<script setup lang="ts">
import { Button, Flex, Form, FormItem, Input, message } from 'ant-design-vue';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRouter } from 'vue-router';

import { login, register } from '@/api/LoginRegister';
import { useValidationRules } from '@/pages/login/loginRegisterCommon';
import ResetPwdModal from '@/pages/login/ResetPwdModal.vue';

export type LoginRegisterFormType = 'login' | 'register';
const props = defineProps<{ formType: LoginRegisterFormType }>();
const emits = defineEmits(['switchTab']);

const { t } = useI18n();
const router = useRouter();
const loginRegFormRef = ref(null);
const loginRegFormData = ref({
  username: '',
  password: '',
  passwordConfirm: '',
});
const validationRules = useValidationRules(loginRegFormData);

const rules = computed(() => {
  const commonRules = {
    username: validationRules.username,
    password: validationRules.password,
  };

  if (props.formType === 'login') return commonRules;
  return {
    ...commonRules,
    passwordConfirm: validationRules.confirmPwd,
  };
});

const submitBtnText = computed(() => ({
  login: t('login.content.login'),
  register: t('login.content.register'),
}));

function submit() {
  const fnMap = { register: submitRegister, login: submitLogin };
  loginRegFormRef.value?.validate().then(() => {
    fnMap[props.formType]?.();
  });
}

async function submitRegister() {
  const { username, password } = loginRegFormData.value;
  const res = await register({ username, password });

  if (res.status === 0) {
    message.success(res.message);
    resetForm();
    switchTab('login');
  } else {
    message.error(res.message);
  }
}

async function submitLogin() {
  const { username, password } = loginRegFormData.value;
  const res = await login({ username, password });

  if (res.status === 0) {
    message.success(res.message);
    resetForm();
    localStorage.setItem('token', res.token);
    await router.replace('/admin/home');
  } else {
    message.error(res.message);
  }
}

function resetForm() {
  loginRegFormData.value = {
    username: '',
    password: '',
    passwordConfirm: '',
  };
  loginRegFormRef.value.resetFields();
  loginRegFormRef.value.clearValidate();
}

function switchTab(tab: LoginRegisterFormType) {
  emits('switchTab', tab);
}

defineExpose({ resetForm });
</script>

<style scoped lang="scss">
.login-form-container {
  .login-button {
    width: 100%;
    height: 40px;
    margin-bottom: 15px;
  }
}
</style>
