// general-backend-management-system-react/src/pages/login/ResetPwdModal.tsx
import { Button, Form, Input, Modal } from 'antd';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { useValidationRules } from '@/pages/login/loginRegisterCommon.ts';

const { Item: FormItem } = Form;
const { Password } = Input;

export default function ResetPwdModal() {
  const { t } = useTranslation();

  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [step, setStep] = useState<number>(1);

  const [step1Form] = Form.useForm();
  const [step2Form] = Form.useForm();
  const [step1FormData, setStep1FormData] = useState({ username: '', email: '' });
  const [step2FormData, setStep2FormData] = useState({ password: '', passwordConfirm: '' });
  const validationRules = useValidationRules(step2FormData);

  const modalFooterBtns = [
    <Button key={'cancel'} onClick={closeModal}>
      {t('login.content.cancel')}
    </Button>,
  ];
  if (step === 1) {
    modalFooterBtns.push(
      <Button key={'next'} type={'primary'} onClick={() => gotoStep(2)}>
        {t('login.content.next')}
      </Button>,
    );
  } else if (step === 2) {
    modalFooterBtns.push(
      <Button key={'prev'} type={'primary'} onClick={() => gotoStep(1)}>
        {t('login.content.prev')}
      </Button>,
      <Button key={'confirm'} type={'primary'} onClick={closeModal}>
        {t('login.content.confirm')}
      </Button>,
    );
  }

  function openModal() {
    setIsModalOpen(true);
  }

  function closeModal() {
    setIsModalOpen(false);
    setStep(1);
    step1Form.resetFields();
    step2Form.resetFields();
  }

  function gotoStep(nextStep: number) {
    if (nextStep === 1) {
      step2Form.resetFields();
      setStep(nextStep);
    } else if (nextStep === 2) {
      step1Form.validateFields().then(() => {
        setStep(nextStep);
      });
    }
  }

  return (
    <>
      <Button type={'link'} onClick={openModal}>
        {t('login.content.forget')}
      </Button>
      <Modal
        open={isModalOpen}
        title={t('login.content.resetPwd')}
        footer={modalFooterBtns}
        centered
        maskClosable={false}
      >
        {step === 1 && (
          <Form
            form={step1Form}
            initialValues={{ username: '', email: '' }}
            layout={'vertical'}
            autoComplete={'off'}
          >
            <FormItem
              name={'username'}
              label={t('login.content.username')}
              rules={validationRules.username}
              validateTrigger={['onBlur', 'onChange']}
              validateFirst
            >
              <Input
                placeholder={t('login.content.usernamePlaceholder')}
                onChange={(e) => setStep1FormData({ ...step1FormData, username: e.target.value })}
              />
            </FormItem>
            <FormItem
              name={'email'}
              label={t('login.content.email')}
              rules={validationRules.email}
              validateTrigger={['onBlur', 'onChange']}
              validateFirst
            >
              <Input
                placeholder={t('login.content.emailPlaceholder')}
                onChange={(e) => setStep1FormData({ ...step1FormData, email: e.target.value })}
              />
            </FormItem>
          </Form>
        )}
        {step === 2 && (
          <Form
            form={step2Form}
            initialValues={{ password: '', passwordConfirm: '' }}
            layout={'vertical'}
            autoComplete={'off'}
          >
            <FormItem
              name={'password'}
              label={t('login.content.password')}
              rules={validationRules.password}
              validateTrigger={['onBlur', 'onChange']}
              validateFirst
            >
              <Password
                placeholder={t('login.content.passwordPlaceholder')}
                onChange={(e) => setStep2FormData({ ...step2FormData, password: e.target.value })}
              />
            </FormItem>
            <FormItem
              name={'passwordConfirm'}
              label={t('login.content.passwordConfirm')}
              rules={validationRules.confirmPwd}
              validateTrigger={['onBlur']}
              validateFirst
            >
              <Password
                placeholder={t('login.content.passwordConfirmPlaceholder')}
                onChange={(e) =>
                  setStep2FormData({ ...step2FormData, passwordConfirm: e.target.value })
                }
              />
            </FormItem>
          </Form>
        )}
      </Modal>
    </>
  );
}

// general-backend-management-system-vue/src/pages/login/ResetPwdModal.vue
<template>
  <Button type="link" @click="showModal">{{ t('login.content.forget') }}</Button>
  <Modal
    v-model:open="isModalVisible"
    :title="t('login.content.resetPwd')"
    :mask-closable="false"
    centered
    @cancel="hideModal"
    @ok="hideModal"
  >
    <Form
      v-show="curStep === 1"
      ref="step1FormRef"
      :model="step1FormData"
      :rules="step1Rules"
      layout="vertical"
    >
      <FormItem :label="t('login.content.username')" name="username">
        <Input
          v-model:value="step1FormData.username"
          :placeholder="t('login.content.usernamePlaceholder')"
          allow-clear
        />
      </FormItem>
      <FormItem :label="t('login.content.email')" name="email">
        <Input
          v-model:value="step1FormData.email"
          :placeholder="t('login.content.emailPlaceholder')"
          allow-clear
        />
      </FormItem>
    </Form>

    <Form
      v-show="curStep === 2"
      ref="step2FormRef"
      :model="step2FormData"
      :rules="step2Rules"
      layout="vertical"
    >
      <FormItem :label="t('login.content.password')" name="password">
        <Input
          v-model:value="step2FormData.password"
          :placeholder="t('login.content.passwordPlaceholder')"
          type="password"
          allow-clear
        />
      </FormItem>
      <FormItem :label="t('login.content.passwordConfirm')" name="passwordConfirm">
        <Input
          v-model:value="step2FormData.passwordConfirm"
          :placeholder="t('login.content.passwordConfirm')"
          type="password"
          allow-clear
        />
      </FormItem>
    </Form>

    <template #footer>
      <Button @click="hideModal">{{ t('login.content.cancel') }}</Button>
      <Button v-if="curStep === 2" type="primary" @click="() => setStep(1)">
        {{ t('login.content.prev') }}
      </Button>
      <Button v-if="curStep === 1" type="primary" @click="() => setStep(2)">
        {{ t('login.content.next') }}
      </Button>
      <Button v-if="curStep === 2" type="primary" @click="hideModal">
        {{ t('login.content.confirm') }}
      </Button>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { Button, Form, FormItem, Input, Modal } from 'ant-design-vue';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { useValidationRules } from '@/pages/login/loginRegisterCommon';

const { t } = useI18n();
const isModalVisible = ref(false);
const curStep = ref<number>(1);
const step1FormRef = ref(null);
const step2FormRef = ref(null);
const step1FormData = ref({
  username: '',
  email: '',
});
const step2FormData = ref({
  password: '',
  passwordConfirm: '',
});

const validationRules = useValidationRules(step2FormData);
const step1Rules = computed(() => ({
  username: validationRules.username,
  email: validationRules.email,
}));
const step2Rules = computed(() => ({
  password: validationRules.password,
  passwordConfirm: validationRules.confirmPwd,
}));

function showModal() {
  isModalVisible.value = true;
}

function hideModal() {
  step1FormData.value = { username: '', email: '' };
  step1FormRef.value?.resetFields();
  step1FormRef.value?.clearValidate();

  step2FormData.value = { password: '', passwordConfirm: '' };
  step2FormRef.value?.resetFields();
  step2FormRef.value?.clearValidate();

  curStep.value = 1;
  isModalVisible.value = false;
}

function setStep(step: number) {
  if (step === 2)
    step1FormRef.value?.validate().then(() => {
      curStep.value = step;
    });
  else if (step === 1) {
    step2FormData.value = { password: '', passwordConfirm: '' };
    step2FormRef.value?.resetFields();
    step2FormRef.value?.clearValidate();
    curStep.value = step;
  }
}
</script>

<style scoped lang="scss"></style>
